spring.application.name=OrdersProcessor

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId} %X{requestMethod} %X{requestPath}] - %msg%n

spring.flyway.clean-disabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# user props
orders.demo.users.page-size=50
orders.demo.users.max-page-size=50
orders.demo.users.default-sort-attribute=username

# orders props
orders.demo.orders.page-size=50
orders.demo.orders.max-page-size=50
orders.demo.orders.products-default-sorting-attribute=name
orders.demo.orders.query-batch-size=100
orders.demo.orders.query-max-size=1000

# ship props
orders.demo.ship.page-size=50
orders.demo.ship.max-page-size=50
orders.demo.ship.shipment-sorting-attribute=shipped,desc
orders.demo.ship.fulfillment-sorting-attribute=created,desc
