spring.application.name=OrdersProcessor

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId} %X{requestMethod} %X{requestPath}] - %msg%n

spring.flyway.clean-disabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# user props
orders.demo.users.pageSize=50
orders.demo.users.maxPageSize=50
orders.demo.users.defaultSortAttribute=username

# orders props
orders.demo.orders.pageSize=50
orders.demo.orders.maxPageSize=50
orders.demo.orders.productsDefaultSortingAttribute=name
orders.demo.orders.queryBatchSize=100
orders.demo.orders.queryMaxSize=1000

# ship props
orders.demo.ship.pageSize=50
orders.demo.ship.maxPageSize=50
orders.demo.ship.shipmentSortingAttribute=shipped,desc
orders.demo.ship.fulfillmentSortingAttribute=created,desc