package spring.orders.demo.users.exceptions;

public enum ApiErrors {

	DUPLICATE_USER,
	USER_NOT_FOUND,
	USER_SERVICE_ERROR,
	INCORRECT_INPUT,
	INTERNAL_ERROR,
	UNAUTHORIZED_OPERATION,
	INCOMPATIBLE_CURRENCIES,
	REQUEST_TOO_BIG

}
