package spring.orders.demo.users.exceptions;

public enum ApiErrors {

	DUPLICATE_USER,
	INCOMPATIBLE_CURRENCIES,
	INCORRECT_INPUT,
	INTERNAL_ERROR,
	PRODUCT_NOT_FOUND,
	REQUEST_TOO_BIG,
	UNAUTHORIZED_OPERATION,
	USER_NOT_FOUND,
	USER_SERVICE_ERROR,
	ORDER_STATUS_DOES_NOT_ALLOW_OP

}
