package spring.orders.demo.exceptions;

public enum ApiErrors {

	DUPLICATE_USER,
	INCOMPATIBLE_CURRENCIES,
	INCORRECT_INPUT,
	INTERNAL_ERROR,
	PRODUCT_NOT_FOUND,
	REQUEST_TOO_BIG,
	UNAUTHORIZED_OPERATION,
	USER_NOT_FOUND,
	USER_SERVICE_ERROR,
	ORDER_STATUS_DOES_NOT_ALLOW_OP,
	FULFILLMENT_NOT_FOUND,
	USER_STATUS_NOT_FOUND,
	EMPTY_PRODUCTS_LIST,
	ORDER_NOT_FOUND,
	BAD_EXISTING_FULFILLMENT_STATUS,
	ORDER_ALREADY_SHIPPED,
	SHIPMENT_NOT_FOUND,
	SHIPMENT_STATUS_NOT_FOUND

}
